kind: pipeline
name: pai7

workspace:
  base: /go
  path: src/github.com/scbizu/pai7

steps:
- name: build
  image: golang:1.13
  environment:
    GO111MODULE: on
  commands:
  - go install

- name: publish_dockerhub
  image: plugins/docker
  settings:
    repo: scnace/pai7
    auto_tag: true
    username:
        from_secret: DOCKERHUB_USER
    password:
        from_secret: DOCKERHUB_PASSWORD
    dockerfile: Dockerfile
